project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*_complete_*.ipynb"
    - "!*.zip"
    - "!*.data"
    - "!datasets/"
    - "!*.names"
    - "!DryBeanDataset/"
    - "!z_recordings/"
    - "!ASRI*/*"
  # post-render:
  #   - "cp images/*.svg docs/images/"
  resources:
    - images/*.svg

website:
  title: "ASRI-2026"
  navbar: false

format:
  html:
    theme: lux
    grid:
      sidebar-width: 0rem
      body-width: 1200px
      margin-width: 0rem
      gutter-width: 1rem
    css: styles.css
    include-in-header:
      - text: |
            <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;500;700&display=swap" rel="stylesheet">
